### ISSUE TITLE
libavfilter/format_cuda_kernel.cu:22:10: fatal error: libavutil/pixfmt.h: No such file or directory

### ISSUE THREAD

**Issue by wkal** [NVIDIA/FFmpeg-GPU-Demo#3]
@xiaoweiw-nv 
Dear weiw,  I followed the REAME's instructions to compile this project, the compilation task was failed, the error info like these:
libavfilter/format_cuda_kernel.cu:22:10: fatal error: libavutil/pixfmt.h: No such file or directory

Platform information: Ubuntu18.04 x64, cuda: 10.2 Nvidia Driver: 510.60.02, gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
My compiling command:
make clean && bash config_ffmpeg_libtorch.sh /home/user/FFmpeg-GPU-Demo/libtorch && make -j5 && sudo make install -j5

**Comment by xiaoweiw-nv** [comment]
This is a strange problem, libavutil/pixfmt.h is part of ffmpeg, should be located in ffmpeg-gpu-demo/ffmpeg-gpu/libavutil/pixfmt.h.

Can you post the output of `make V=1`? It shows the detailed compiler options.

**Comment by xiaoweiw-nv** [comment]
@wkal We have added a Dockerfile to the repo, please check out the new readme and docs.

Closing the issue due to long inactivity.
