### ISSUE TITLE
It seems didn't have supported on jetson device

### ISSUE THREAD

**Issue by DeserterW** [NVIDIA/FFmpeg-GPU-Demo#4]
I found it seem this ffmpeg didn't have jetson supported. Just remain a issue for question. Will it supports it in future?

**Comment by xiaoweiw-nv** [comment]
> I found it seem this ffmpeg didn't have jetson supported. Just remain a issue for question. Will it supports it in future?

Thanks for noticing. We are focusing on datacenter at this moment, as our target scenario is cloud video processing. Could you list some target applications on jetson devices which may involve GPU ffmpeg?
